M48
; DRILL file {KiCad (6.0.1)} date Fri May 20 13:53:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-20T13:53:33-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
%
G90
G05
T1
X5.4149Y-2.7081
X5.5067Y-2.6337
X6.1613Y-2.6237
X6.2531Y-2.6981
T0
M30
